[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm>=6.2"
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.semantic_release]
version_variable = "setup.py:__version__"
