---
title: "Introduction to youte"
author: "Digital Observatory"
format: 
  html:
    css: styling_doc.css
editor: visual
---

YouTube is the second most visited website in the world \[[1](https://www.semrush.com/website/top/)\], with 81% of Internet users having used the site \[[2](https://blog.hootsuite.com/youtube-stats-marketers/)\]. That's nearly everyone! On average, over 500 hours of videos are uploaded. This makes YouTube an invaluable source of social media data for the research community. There is much to be studied not only in the video content itself, but also in the metadata such as video titles, descriptions, and comments.

A body of research has done analyses using YouTube data, with topics ranging from cyber influence to misinformation. Here are a few examples:

-   https://ieeexplore.ieee.org/document/8508766

-   https://www.sciencedirect.com/science/article/pii/S0167923617300994

-   https://link.springer.com/chapter/10.1007/978-3-030-67044-3_5

-   https://www.frontiersin.org/articles/10.3389/fcomm.2019.00036/full

-   https://dl.acm.org/doi/pdf/10.1145/3359196

`youte` was developed with the aim to help researchers or anyone to collect YouTube data quickly and easily.

## Introduction to youte

`youte` is a helper library that interacts with YouTube Data API. Effectively, it makes working with YouTube API and collecting YouTube metadata and comments easy and intuitive.

`youte` is a command-line tool that runs in the Terminal and can be installed in any operating system.

### About YouTube Data API

For those unfamiliar with the acronym, API or Application Programming Interface is a set of communication protocols that help two programs or applications talk with each other.

YouTube Data API allows you to work with YouTube data. You make a request for data to the API, and in return it sends you a response which contains the data requested.

#### What kind of data does YouTube Data API give?

With YouTube Data API you can get information on a variety of **resources**. A YouTube resource is an entity that makes up the YouTube experience. Some common resources include videos, channels, comments, playlists, and search results.

### Command-line

We mentioned that `youte` is a command-line tool. So what is a command line? A command line, or the shell, is an interface that takes textual, keyboard commands and passes them to your computer to carry them out.

Examples in OS:

-   Windows: cmd, Powershell, Git Bash

-   Linux & Mac OS: bash or zsh terminal

If you need a quick reminder how the shell works, here is a useful resource: https://swcarpentry.github.io/shell-novice/.

For the sake of simplicity, for this tutorial we'll be using the Bash shell, which is available by default in Linux and Mac OS, and can be accessed in Windows via Git Bash.

*Code display convention*: Shell commands in this tutorial are displayed as codes with a dollar (\$) sign in front of them. When copying the code to your own terminal, make sure to omit the dollar sign.

## Using youte

### Installing youte

To install youte, run:

``` shell
pip install youte
```

`youte` can work with Python 3.8 and above, so make sure you check your Python version before installing.

### Set up

To get started, you will need a YouTube API key. Obtaining a key is simple and straightforward, but you will need a Google account to do so. Instructions for getting an API key are described in this link: https://developers.google.com/youtube/v3/getting-started.

Once you have your API key, configure your key with `youte` by running the command:

``` shell
youte config add-key
```

The command will start an interactive prompt where you enter your API key and give it a name. This will store your API key in a config file which `youte` will use when running queries. You're also asked if you want to set a key as the default key. If there is a default key, it will be used every time you run a query when no API key is specified.

To see a list of all stored keys, run:

``` shell
youte config list-keys
```

### Running a search

Now, onto the exciting part. Let's run a search!

Similarly to doing a YouTube search, `youte search` allows you to do get a list of videos matching keywords and other specified criteria. Of course you will not get the video content itself, but the metadata such as video titles and descriptions.

Here is the format of `youte search` command:

``` shell
youte search <QUERY> <OUTPUT> --from <YYYY-MM-DD> --to <YYYY-MM-DD> --name <name-of-api-key> --order=date --safe-search=none
```

-   `QUERY`: the search term to look for in YouTube video titles and descriptions

-   `OUTPUT`: name of the file to store raw JSON responses from the API

-   `--from`, `--to`: specify date range of the search results returned. These are optional.

-   `--name`: name of the API key configured with youte. This is optional if you already have a default API key set up.

-   `--order`: sort type. The default is sort the results by date of upload.

-   `--safe-search`: include or exclude restricted content. The default is to include all public content.

As an example, let's search for videos matching "offgrid" from last month.

``` shell
youte search "offgrid" results.json --from 2022-08-01 --to 2022-08-31
```

Of course, you might want to get just the most relevant results first:

``` shell
youte search "offgrid" results.json --from 2022-08-01 --to 2022-08-31 --order=relevance
```

Maybe only include moderated content:

``` shell
youte search "offgrid" results.json --from 2022-08-01 --to 2022-08-31 --safe-search=moderate
```

Results returned are in JSON format.

*What is JSON?*

JSON is the most common way for exchanging text data. Today it is the universal standard of data exchange because of its conciseness, versatility, and platform independence. There are tools to work with JSON in most languages.

Here is an example of a JSON file.

``` json
{
  "kind": "youtube#searchResult",
  "etag": "B_TxCObncAju-vhnFwKefxRoNRI",
  "id": {
    "kind": "youtube#video",
    "videoId": "SR2Mf27YweM"
  },
  "snippet": {
    "publishedAt": "2022-08-31T00:43:25Z",
    "channelId": "UCnSc_XzYmAMMSJX4shj7ovw",
    "title": "30/08/22 :: 9 HOURS STUDY WITH ME [PART-2/2] :: CA: UPSC: PCS: IIT: NEET: SSC: OTHER EXAMS",
    "description": "Why is this channel ? As we know that to get good marks in any exam ,we have to study hard and for which consistency is ...",
    "thumbnails": {
      "default": {
        "url": "https://i.ytimg.com/vi/SR2Mf27YweM/default.jpg",
        "width": 120,
        "height": 90
      },
      "medium": {
        "url": "https://i.ytimg.com/vi/SR2Mf27YweM/mqdefault.jpg",
        "width": 320,
        "height": 180
      },
      "high": {
        "url": "https://i.ytimg.com/vi/SR2Mf27YweM/hqdefault.jpg",
        "width": 480,
        "height": 360
      }
    },
    "channelTitle": "BE CONSISTENT",
    "liveBroadcastContent": "none",
    "publishTime": "2022-08-31T00:43:25Z"
  }
}
```

Everything inside a curly braces belongs an object. An object is basically a thing or an entity. Within that object you can have object properties or attributes, represented by key-value pairs. You can have objects nested within objects as well.

There are many tools to view and work with JSON files. Here I'm using `jq` (https://stedolan.github.io/jq/) which is a commandline tool, to view the JSON.

As you can see, the JSON format is great for data exchange, but not for data analysis, for which you'll probably need something closer to a table or spreadsheet. I'll talk about transforming JSON to a tabular format in `youte` later on.

### Hydrate

Now, if you look at the search results, you'll see that they only contain some information. The video description is truncated, and no video statistics are provided. `youte search` only returns some data, so if you want to get full data on a set of videos or channels you might need to use `hydrate`.

The `hydrate` gets you more information about a resource from a list of resource IDs. The resource here can be video or channel. A resource ID is a unique identifier given to every YouTube resource. So every video, channel, comment, and user have an ID, and you will see them in the browser or within the search results set returned by `youte search`.

The video ID is the query string `v=` in your URL when you click on a YouTube video.

https://www.youtube.com/watch?v=**5MXTcO1veRQ**

``` shell
youte hydrate [OPTIONS] OUTPUT [ITEMS]...
```

Here you specify the output file name, followed by as many item IDs as you want. Make sure you separate the IDs by a space. By default, the command will take these IDs as video IDs and hydrate video data. If you want instead to hydrate a list of channel IDs, specify the `--channel` flag.

Instead of listing the IDs in the shell, you can also specify a file containing the IDs by passing the `-f` flag followed by the file's path. The file should contain just the IDs, each on a new line, and of the same resource type. So either all video IDs or all channel IDs in one file.

### Get comments on a video

What if you want all the comments under a video? The `youte list-comments` command lets you do just that.

``` shell
youte list-comments -v OUTPUT [ITEMS]...
```

The format of `list-comments` is the same as `hydrate`. You specify a name for the output file, followed by one or multiple video IDs. Remember to pass the `-v` flag to indicate that the IDs are video IDs, and you want to get comments for these videos.

One potential issue you might run into when running this command is if the video has comments disabled. In this case, the program will show a warning and continue to other IDs if there is any.

Similarly to `hydrate`, you can also use IDs from a text file instead of passing them to the shell, by using the `-f` flag.

### Get replies to comments

Getting comments on a video retrieve the top level comments (or *threads)*, but not their replies. You can get the replies to a thread by running `list-comments` with the thread ID, and passing `-t` to indicate the ID belongs to a thread, not a video.

The thread ID can be seen if you hover your mouse over a comment's timestamp.

https://www.youtube.com/watch?v=A-mO7rbYtgk&lc=**UgwTqVJTgz1gZl6X57Z4AaABAg**

``` shell
youte list-comments -t OUTPUT [ITEMS]...
```

This command will return an empty JSON if there are no replies.

### Tidy

Now that you have a bunch of JSON files collected from YouTube. How are you going to process and analyse them?

As I have mentioned before, JSON is not great for analyses, which normally require data to be in some tabular, spreadsheet like format. This is where `youte tidy` might come in handy, in that it processes and transforms raw JSON files into a relational, SQLite database.

A relational database contains tables of columns and rows. Each row represents an entity (object) and each column an attribute of that entity. So it looks very similar to your spreadsheet or CSV file. SQLite is a light-weight database engine that stores an entire database within a `.db` file. You use SQL to query or update data in a database. You might or might not have worked with SQL, but don't worry: the commands most commonly used to work with databases are fairly easy to understand.

Now, let's see what `youte tidy` does. It takes in a single JSON file as input, and a `.db` file as output.

``` shell
youte tidy raw.json cleaned.db
```

The JSON file should contain ***one*** type of resource (e.g. video, channel, comment). And the output file must have a `.db` ending.

Now that you have a database of cleaned data ready. Let's examine the data.

There are many tools to work with SQlite files, in R and Python. In R, the `RSQLite` package offers a nice easy way to interact and read data from `.db` files.

``` r
library(DBI)     #for createing database connection
library(RSQLite)

con <- DBI::dbConnect(RSQLite::SQLite(), "comments.db")
dbListTables(con)             #list all tables in the database
data <- dbReadTable(con, "comments")  #get table `comments` to a dataframe
```

## Wrapping up

Comments or feedback?

Extra help doc
