---
title: "youte: Collecting YouTube video metadata and comments"
---

## About `youte`

`youte` is a helper library that interacts with [YouTube Data API](https://developers.google.com/youtube/v3). Effectively, it makes working with YouTube API and collecting YouTube metadata and comments easy and intuitive. `youte` is primarily run as a command-line tool.

`youte` is still early in its development, so its functionalities remain quite limited. However, the tool is actively worked on and new capabilities are being added at the present. Keep an eye out for new releases on our [GitHub page](https://github.com/QUT-Digital-Observatory/youte): 

### YouTube Data API

An *Application Programming Interface* or API is a set of communication protocols that help two programs or applications talk to each other. According to this protocol, you send a request to the API, and the API returns a response code to tell you whether your request was valid, and a response body that contains the data requested.

As an API, [YouTube Data API](https://developers.google.com/youtube/v3/getting-started) allows you to get information of a wide range of resources. A YouTube [*resource*](https://developers.google.com/youtube/v3/getting-started#resources) is an entity that makes up the YouTube experience, including video, channel, playlist, comment, and search results. Each resource has a unique ID given by YouTube. These IDs will come in handy when you query data from YouTube API.

The API also allows you to update, delete or create YouTube resources, although as a data collection tool, `youte` currently does not support these operations.

### Command-line

We mentioned that `youte` is a command-line tool. So what is a command line? A *command line*, or the *shell*, is an interface that takes textual, keyboard commands and passes them to your computer for execution.

A variety of shells are used across operating systems. Some common ones are listed below:

-   Windows: Command Prompt (cmd), Powershell, Git Bash

-   Linux & Mac OS: Bash, Zsh

If you need a quick introduction of how the shell works, [this guide](https://swcarpentry.github.io/shell-novice/) is a useful resource.

*Code display convention*: Shell commands in this tutorial are displayed as codes with a dollar (\$) sign in front of them. When copying the code to your own terminal, make sure to omit the dollar sign.

## Installing youte

To install youte, run:

``` shell
$ python -m pip install youte
```

`youte` can work with Python 3.8 and above, so make sure you check your Python version before installing.

### Issues installing `youte` in Anaconda

If you use Anaconda's distribution of Python, there might be issues installing and using `youte`. The below solutions have been tried and shown to work:

- If you install `youte` in the base environment (i.e. not in a virtual environment), run `youte` in Anaconda Prompt as opposed to other shells.

- You can install `youte` in a virtual environment and run it in that virtual environment.

## Set up

To get started, you will need a YouTube API key. Obtaining an API key is simple and straightforward, but you will need a Google account to do so. Instructions for getting an API key are described [here](https://developers.google.com/youtube/v3/getting-started).

Once you have your API key, configure your key with `youte` by running the command:

``` shell
$ youte config add-key
```

This will display an interactive prompt where you enter your API key and give it a name. The name will be used to specify the API key, and it can be anything you choose. This will save you the trouble of having to enter the API key every time you query data from YouTube: all you need is the key's name.

You're also asked if you want to set a key as the default key. If there is a default key, it will be used automatically every time you run a query.

All API keys have to be added to `youte` before they can be used. `config add-key` stores your API key in a config file which `youte` will refer to when running queries. The config file also stores metadata such as your quota usage and time of its most recent use.

To see a list of all stored keys, run:

``` shell
$ youte config list-keys
```

To manually set a key as a default, run:

``` shell
$ youte config set-default <NAME-OF-KEY>
```

Here you specify the *name* of the API key you want to set as default.

To remove an API key from `youte`, run:

```shell
$ youte config remove <NAME-OF-KEY>
```

## Running a search

Now, onto the exciting part. Let's run a search!

Similarly to doing a YouTube search, `youte search` allows you to do get a list of videos matching keywords and other specified criteria. `youte` does not return audiovisual content, just the metadata such as video titles and descriptions.

Here is the format of `youte search` command. Note that all shell commands must be inputted in one line. The backlashes (`\`) are used to enter a new line without breaking the command and help with readability.

``` shell
$ youte search <QUERY> <OUTPUT> \
    --from <YYYY-MM-DD> \
    --to <YYYY-MM-DD> \
    --name <name-of-api-key> \
    --order=<date|rating|relevance|title> \
    --safe-search=<none|moderate|strict>
```

The \<QUERY\> and \<OUTPUT\> are must-have arguments and have to follow the order specified in the command.

-   `QUERY`: the search term to look for in YouTube video titles and descriptions.

-   `OUTPUT`: name of the file to store raw JSON responses from the API. The file must end in `.json` or `.jsonl`.

Besides the above, there are several optional arguments that you can pass to further refine the search:

-   `--from`, `--to`: specify date range of the search results returned. The date format has to follow ISO format (YYYY-MM-DD). Note that the date range here is *inclusive*.

-   `--name`: name of the API key configured with `youte`. This is optional if you already have a default API key set up.

-   `--order`: specify how you want the data to be sorted. The default (`date`) will sort the results by date of upload. Other options include `rating`, `relevance`, and `title`.

-   `--safe-search`: include or exclude restricted content. The default (none) will include all publicly available content. Other options include `moderate`, and `strict`.

As an example, let's search for videos matching "offgrid living" in August 2022.

``` shell
youte search "offgrid living" results.json --from 2022-08-01 --to 2022-08-31
```

Of course, you might want to get just the most relevant results first:

``` shell
youte search "offgrid living" results.json --from 2022-08-01 --to 2022-08-31 --order=relevance
```

Or only include moderated content:

``` shell
youte search "offgrid living" results.json --from 2022-08-01 --to 2022-08-31 --safe-search=moderate
```

### Saving search progress

As will be described below, often there is a limit to how much data you get from YouTube API per day. Searching, in particular, is very "expensive" in terms of API usage. Therefore, you can choose to save the progress of a search so that if you exit the program prematurely, either by accident or on purpose, you can resume the search to avoid wasting valuable quota units.

Specifically, when you exit the program in the middle of a search, a prompt will ask if you want to save its progress. If yes, progress of the search is saved in a database, whose name matches exactly the name of the `OUTPUT` file that you specified. If you rerun the same search in the same directory, you can choose to resume the progress from that database. This database will be deleted once all search results have been returned.

``` shell
$ youte search "offgrid living" --from 2022-08-08 --output search_offgrid.json  
```

``` text

# exit program
Do you want to save your current progress? [y/N]: # y  

# resume search
$ youte search "offgrid living" --from 2022-08-08 --output search_offgrid.json  

Getting API key from config file.  

        A history file '.youte.history/search_offgrid.db' is detected in your current directory.
        Do you want to resume progress from this history file?
        If you are at all unsure, say No. [y/N]:
```

## Hydrating videos and channels

Now, if you look at the search results returned from `youte search`, you'll see that they contain only a few fields of information. For example, video statistics are not provided, and video descriptions are truncated.

`youte search` only returns some data, so if you want to get full data on a set of videos or channels you might need to use `hydrate`.

``` shell
youte hydrate [OPTIONS] <OUTPUT> <ITEMS>...
```

- `OUTPUT`: name of the file to store raw JSON responses from the API. The file must end in `.json` or `.jsonl`.
- `ITEMS`: one or more video IDs separated by a space. 

`youte hydrate` command takes as input a list of video or channel IDs and retrieves information on those. As mentioned above, each YouTube resource has a unique identifier. You can get the ID of a resource in the browser or within the data returned by YouTube Data API. For example, the ID of a YouTube video can be seen in the video's URL:

https://www.youtube.com/watch?v=**5MXTcO1veRQ**

Now let's hydrate this video. By default, `youte hydrate` takes the IDs as video IDs and return video information. So you can hydrate one video easily with:

``` shell
$ youte hydrate video.json 5MXTcO1veRQ
```

You can also hydrate multiple videos:

``` shell
$ youte hydrate videos.json 5MXTcO1veRQ cbAj3biUeDI dTI3I9ZFzTI
```

### Hydrating channels

If you want to hydrate a list of channel IDs, pass the `--channel` flag.

Hydrate 1 channel ID:

``` shell
$ youte hydrate channel.json --channel UC3mORGO2XYSn3Y_BUPuazeQ
```

Hydrate multiple channel IDs

```shell
$ youte hydrate channels.json --channel UCC-jcZTFL1r17E-bEC7VYYA UC3mORGO2XYSn3Y_BUPuazeQ
```

#### Working with channel IDs 

Similar to video IDs, channel IDs can be found in the channels' URLs (https://www.youtube.com/channel/**UC3mORGO2XYSn3Y_BUPuazeQ**). 

However, most often channel IDs will be more difficult to find because YouTube channels can have custom names and URLs (e.g. https://www.youtube.com/c/**AmbitionMusic**), or older channels might have a different URL (e.g. https://www.youtube.com/user/QueenAnime141). These custom names won't be able to hydrate.

Therefore, the best way to get channel IDs is in the search results from `youte search`.

### Using file containing IDs

Instead of listing the IDs in the shell, you can also specify a file containing the IDs by passing the `-f` flag followed by the file's path. The file should contain just the IDs, each on a new line, and of the same resource type.

``` shell
$ youte hydrate videos_json -f video_ids.csv
```

## Getting comments

### Getting comments on video

The `youte list-comments` command lets you retrieve comments left on a video or to a comment thread. First, let's get comments on a video.

``` shell
$ youte list-comments -v <OUTPUT> <ITEMS>...
```

The format of `list-comments` is the same as `hydrate`. You specify a name for the output file, followed by one or multiple video IDs. Remember to pass the `-v` flag to indicate that the IDs are video IDs from which to get comments.

``` shell
$ youte list-comments -v comments.json dTI3I9ZFzTI
```

One potential issue you might run into when running this command is if the video has comments disabled. In this case, the program will show a warning and skip to other IDs if there is any.

### Getting replies to comment threads

Getting comments on a video retrieves only the top level comments (or *threads*), but not their replies. You can get the replies to a thread by running `list-comments` with the thread ID, and passing `-t` to indicate the ID belongs to a thread, not a video.

In a browser, the thread ID can be seen if you hover your mouse over a comment's timestamp. Or you can get the thread IDs from the data returned by `list-comments`.

https://www.youtube.com/watch?v=A-mO7rbYtgk&lc=**UgwTqVJTgz1gZl6X57Z4AaABAg**


``` shell
$ youte list-comments -t <OUTPUT> <ITEMS>...
```

This command will return an empty JSON if there are no replies.

#### Using text file containing IDs

Similarly to `hydrate`, you can also use IDs from a text file instead of passing them to the shell, by using the `-f` flag.

``` shell
$ youte list-comments -v comments_many.json -f video_ids.csv
```

## Tidying data

### JSON format

All data returned from `youte search`, `youte hydrate`, and `youte list-comments` are in JSON format.

*What is JSON?*

[JSON](https://www.w3schools.com/js/js_json_intro.asp) is the most common way for exchanging text data. Today it is the universal standard of data exchange because of its conciseness, versatility, and platform independence.

Here is an example of a JSON object.

``` json
{
  "kind": "youtube#searchResult",
  "etag": "B_TxCObncAju-vhnFwKefxRoNRI",
  "id": {
    "kind": "youtube#video",
    "videoId": "SR2Mf27YweM"
  },
  "snippet": {
    "publishedAt": "2022-08-31T00:43:25Z",
    "channelId": "UCnSc_XzYmAMMSJX4shj7ovw",
    "title": "30/08/22 :: 9 HOURS STUDY WITH ME [PART-2/2] :: CA: UPSC: PCS: IIT: NEET: SSC: OTHER EXAMS",
    "description": "Why is this channel ? As we know that to get good marks in any exam ,we have to study hard and for which consistency is ...",
    "thumbnails": {
      "default": {
        "url": "https://i.ytimg.com/vi/SR2Mf27YweM/default.jpg",
        "width": 120,
        "height": 90
      },
      "medium": {
        "url": "https://i.ytimg.com/vi/SR2Mf27YweM/mqdefault.jpg",
        "width": 320,
        "height": 180
      },
      "high": {
        "url": "https://i.ytimg.com/vi/SR2Mf27YweM/hqdefault.jpg",
        "width": 480,
        "height": 360
      }
    },
    "channelTitle": "BE CONSISTENT",
    "liveBroadcastContent": "none",
    "publishTime": "2022-08-31T00:43:25Z"
  }
}
```

Everything inside a curly braces belongs to an object. An *object* is basically a thing or an entity. Within that object, you can have object properties or attributes, represented by key-value pairs. As shown in the example above, you can also have objects nested within objects.

As you can see, the JSON format is great for data exchange, but not for data analysis, for which you'll probably need something closer to a table or spreadsheet. This is where `youte tidy` might come in handy, as it processes and transforms raw JSON files into a relational, SQLite database.

A relational database contains tables of columns and rows. Each row represents an entity (object) and each column an attribute of that entity. So it looks very similar to your spreadsheet or CSV file. SQLite is a light-weight database engine that stores an entire database within a `.db` file, making it easy to transfer and work with small-scale databases. Interacting with databases requires [SQL](https://www.w3schools.com/sql/sql_intro.asp), although there are tools and libraries that will minimise the amount of SQL you'll need to read data. 

Now, let's see what `youte tidy` does. It takes in a single JSON file as input, and a `.db` file as output.

``` shell
youte tidy <INPUT-JSON> <OUTPUT-DB>
```

The JSON file should contain ***one*** type of resource (e.g. video, channel, comment). And the output file must have a `.db` ending.

``` shell
youte tidy raw.json cleaned.db
```

### Working with databases in R and Python

#### R

There are many tools to work with SQlite files, in R and Python. In R, the `RSQLite` package offers a nice and easy way to interact and read data from `.db` files.

``` r
library(DBI)     # for createing database connection
library(RSQLite)

con <- DBI::dbConnect(RSQLite::SQLite(), "comments.db")
dbListTables(con)             # list all tables in the database
data <- dbReadTable(con, "comments")  # get table `comments` to a dataframe
```

#### Python

The `pandas` library offers some nice functions to connect with and read data from databases. pandas' `read_sql_query` lets you query a database into a DataFrame.

``` python
import pandas
import sqlite3   # for creating connection with SQLite databases

con = sqlite3.connect("cleaned.db")   # connect to cleaned.db
data = pandas.read_sql_query("SELECT * FROM comments", con=con)  # read all data from table "comments" to a pandas DataFrame
```

## YouTube API Quota system

Most often, there is a limit to how many requests you can make to YouTube API per day. YouTube API uses a quota system in which each request costs a number of units depending on the operation requested.

For example:

- searching costs 100 units per request

- hydrating videos, channels, and comments each costs 1 unit per request

Free accounts get an API quota cap of 10,000 units per project per day, which resets at midnight Pacific Time. Hence the default maximum quota value is set to be 10,000 in `youte`.

### `youte`'s handling of quota usage

At present, you can only check your quota usage on the [Quotas](https://console.cloud.google.com/iam-admin/quotas) page in the API Console. It is not possible to monitor quota usage via metadata returned in the API responses.

Therefore, `youte` manually monitors quota by keeping counts of requests made and logging their quota usage to the config file. If the maximum quota has been reached, youte handles it by putting the program to sleep until quota reset time (midnight Pacific) before re-running the collector. This is a makeshift approach and does not guarantee perfectly accurate data, especially when you try to collect data on multiple computers using the same API key.

### Saving search progress

As you have seen above, searching is very "expensive" in terms of quota usage. Therefore, you can select to save the progress of a search so that if you exit the program prematurely, either by accident or on purpose, you can resume the search from where it stopped to avoid wasting valuable quota units.

When you exit the program in the middle of a search (i.e. by pressing Ctrl+C), you will get a prompt asking to save progress. 

If you select Yes, search progress is saved in a SQLite database in a hidden *.youte.history* folder inside your current directory. The name of the database is what is passed as the OUTPUT file with the `.json` extension removed. If you rerun the same search in the same directory, you can choose to resume the progress from that database. This database will be deleted once all search results have been returned.

``` shell
$ youte search "offgrid living" search.json
```

When you press Ctrl+C to exit the program midway through and then press `y` after the prompt you will see:

```
Do you want to save your current progress? [y/N]:

Progress saved at /home/boyd/Documents/demo/.youte.history/search.db
```

To resume the search, type the same command in the same directory:

``` shell
$ youte search "offgrid living" search.json
```

```
A history file '.youte.history/search.db' is detected in your current directory.
Do you want to resume progress from this history file?
If you are at all unsure, say No. [y/N]:
```

## Feedback is welcome!

`youte` is still in its infancy, and we are working to improve and expand its capabilities. Extra documentation on `youte` can be found on our [GitHub's repository](https://github.com/QUT-Digital-Observatory/youte). Let us know your feedback or suggestions by creating GitHub issues or emailing us at [digitalobservatory@qut.edu.au](mailto:digitalobservatory@qut.edu.au).
 